"""Versioned, local-only compiled retrieval sidecars.

The authority remains SQLite.  A sidecar is a disposable materialized view of
one immutable graph version and is accepted only when its memory id, graph
version, graph checksum and compiled schema all match SQLite.  Files are
memory-mapped while unpickling so concurrent workers share the input pages and
do not allocate an additional serialized byte buffer; the reconstructed Python
indexes remain private to each worker.

Pickle is intentionally used only for artifacts generated by this package in a
trusted local directory.  Operators must not point ``compiled_cache_dir`` at a
directory writable by an untrusted user.
"""
from __future__ import annotations

from dataclasses import dataclass, replace
import enum
import hashlib
import json
import mmap
import os
from pathlib import Path
import pickle
import sys
import tempfile
import threading
import time
import types
from typing import Mapping

from ..domain import EvidenceMember, SourceTurn
from ..principals import PrincipalRegistry
from ..runtime import GraphReadView
from .seeding import TurnSearchIndex


COMPILED_MEMORY_SCHEMA = "graphmem-v5.11-compiled-memory-v2"


def retained_size_bytes(root: object) -> int:
    """Count the unique Python objects retained by ``root``.

    This is deliberately an offline/cold-path operation.  Unlike the old row
    heuristic it includes strings, postings, adjacency tuples, counters and
    dataclass fields while deduplicating shared references by object identity.
    Runtime cache eviction can therefore use the measured retained footprint
    embedded in the artifact without rescanning it in every worker.
    """
    seen: set[int] = set()
    stack = [root]
    total = 0
    atomic = (str, bytes, bytearray, memoryview, int, float, bool, type(None))
    ignored = (type, types.ModuleType, types.FunctionType,
               types.BuiltinFunctionType, types.MethodType, enum.Enum)
    while stack:
        value = stack.pop()
        identity = id(value)
        if identity in seen:
            continue
        seen.add(identity)
        total += sys.getsizeof(value)
        if isinstance(value, dict):
            stack.extend(value.keys())
            stack.extend(value.values())
        elif isinstance(value, (tuple, list, set, frozenset)):
            stack.extend(value)
        elif isinstance(value, atomic) or isinstance(value, ignored):
            continue
        elif hasattr(value, "__dict__"):
            stack.append(vars(value))
        else:
            for cls in type(value).__mro__:
                slots = getattr(cls, "__slots__", ())
                if isinstance(slots, str):
                    slots = (slots,)
                for slot in slots:
                    if (slot not in {"__dict__", "__weakref__"}
                            and hasattr(value, slot)):
                        stack.append(getattr(value, slot))
    return total


@dataclass(frozen=True, slots=True)
class CompiledMemoryArtifact:
    """All immutable structures needed before QueryIR compilation begins."""

    schema_version: str
    memory_id: str
    graph_version: int
    graph_checksum: str
    created_ns: int
    view: GraphReadView
    turns: tuple[SourceTurn, ...]
    turn_by_id: Mapping[str, SourceTurn]
    turn_by_session_index: Mapping[tuple[str, int], str]
    turn_index: TurnSearchIndex
    groups_by_turn: Mapping[str, tuple[str, ...]]
    turns_by_group: Mapping[str, tuple[str, ...]]
    members_by_group: Mapping[str, tuple[EvidenceMember, ...]]
    principals: PrincipalRegistry
    view_retained_bytes: int = 0
    total_retained_bytes: int = 0

    def with_accounting(self) -> "CompiledMemoryArtifact":
        view_bytes = retained_size_bytes(self.view)
        provisional = replace(self, view_retained_bytes=view_bytes)
        return replace(
            provisional, total_retained_bytes=retained_size_bytes(provisional))


class CompiledMemorySidecar:
    """Atomic reader/writer and telemetry for versioned compiled artifacts."""

    def __init__(self, root: str | Path) -> None:
        self.root = Path(root)
        self._lock = threading.Lock()
        self._stats: dict[str, int | float] = {
            "hits": 0, "misses": 0, "invalid": 0, "errors": 0,
            "writes": 0, "bytes_mapped": 0, "bytes_written": 0,
            "load_ms": 0.0, "write_ms": 0.0,
        }

    @staticmethod
    def _name(memory_id: str) -> str:
        digest = hashlib.sha256(memory_id.encode("utf-8")).hexdigest()
        readable = "".join(
            char if char.isalnum() or char in "-_" else "_"
            for char in memory_id)[:48].strip("_") or "memory"
        return f"{readable}.{digest[:20]}.gmc"

    def path_for(self, memory_id: str) -> Path:
        return self.root / self._name(memory_id)

    def metadata_path_for(self, memory_id: str) -> Path:
        return self.path_for(memory_id).with_suffix(".gmc.meta.json")

    def is_current(self, memory_id: str, graph_version: int,
                   graph_checksum: str) -> bool:
        """Check the tiny publish record without unpickling a multi-GB corpus.

        Runtime readers still validate the complete artifact in :meth:`load`.
        This record exists only so the background publication monitor can poll
        graph versions cheaply instead of mmap/unpickling every current view.
        """
        target = self.path_for(memory_id)
        metadata = self.metadata_path_for(memory_id)
        try:
            payload = json.loads(metadata.read_text(encoding="utf-8"))
            return (
                target.is_file()
                and payload.get("schema_version") == COMPILED_MEMORY_SCHEMA
                and payload.get("memory_id") == memory_id
                and int(payload.get("graph_version", -1)) == graph_version
                and payload.get("graph_checksum") == graph_checksum
                and int(payload.get("serialized_bytes", -1)) == target.stat().st_size
            )
        except (OSError, ValueError, TypeError, json.JSONDecodeError):
            return False

    def _add(self, **values: int | float) -> None:
        with self._lock:
            for key, value in values.items():
                self._stats[key] += value

    def load(self, memory_id: str, graph_version: int,
             graph_checksum: str) -> CompiledMemoryArtifact | None:
        path = self.path_for(memory_id)
        if not path.is_file():
            self._add(misses=1)
            return None
        started = time.perf_counter()
        try:
            size = path.stat().st_size
            with path.open("rb") as handle:
                with mmap.mmap(handle.fileno(), 0, access=mmap.ACCESS_READ) as mapped:
                    artifact = pickle.Unpickler(mapped).load()
        except (OSError, ValueError, EOFError, pickle.PickleError, ImportError,
                AttributeError, TypeError):
            self._add(errors=1, load_ms=(time.perf_counter() - started) * 1000)
            return None
        valid = (
            isinstance(artifact, CompiledMemoryArtifact)
            and artifact.schema_version == COMPILED_MEMORY_SCHEMA
            and artifact.memory_id == memory_id
            and artifact.graph_version == graph_version
            and artifact.graph_checksum == graph_checksum
            and artifact.view.graph_version == graph_version
            and artifact.view.graph_checksum == graph_checksum
        )
        elapsed_ms = (time.perf_counter() - started) * 1000
        if not valid:
            self._add(invalid=1, load_ms=elapsed_ms)
            return None
        self._add(hits=1, bytes_mapped=size, load_ms=elapsed_ms)
        return artifact

    def save(self, artifact: CompiledMemoryArtifact) -> Path:
        if artifact.schema_version != COMPILED_MEMORY_SCHEMA:
            raise ValueError("compiled artifact schema does not match this runtime")
        self.root.mkdir(parents=True, exist_ok=True)
        target = self.path_for(artifact.memory_id)
        metadata_target = self.metadata_path_for(artifact.memory_id)
        started = time.perf_counter()
        temporary: Path | None = None
        metadata_temporary: Path | None = None
        try:
            with tempfile.NamedTemporaryFile(
                    mode="wb", prefix=f".{target.name}.", suffix=".tmp",
                    dir=self.root, delete=False) as handle:
                temporary = Path(handle.name)
                pickle.dump(artifact, handle, protocol=5)
                handle.flush()
                os.fsync(handle.fileno())
            os.chmod(temporary, 0o600)
            os.replace(temporary, target)
            size = target.stat().st_size
            publish_record = {
                "schema_version": artifact.schema_version,
                "memory_id": artifact.memory_id,
                "graph_version": artifact.graph_version,
                "graph_checksum": artifact.graph_checksum,
                "created_ns": artifact.created_ns,
                "serialized_bytes": size,
                "view_retained_bytes": artifact.view_retained_bytes,
                "total_retained_bytes": artifact.total_retained_bytes,
            }
            with tempfile.NamedTemporaryFile(
                    mode="w", encoding="utf-8", prefix=f".{metadata_target.name}.",
                    suffix=".tmp", dir=self.root, delete=False) as handle:
                metadata_temporary = Path(handle.name)
                json.dump(publish_record, handle, sort_keys=True)
                handle.write("\n")
                handle.flush()
                os.fsync(handle.fileno())
            os.chmod(metadata_temporary, 0o600)
            os.replace(metadata_temporary, metadata_target)
        except BaseException:
            for candidate in (temporary, metadata_temporary):
                if candidate is not None:
                    try:
                        candidate.unlink()
                    except FileNotFoundError:
                        pass
            raise
        self._add(
            writes=1, bytes_written=size,
            write_ms=(time.perf_counter() - started) * 1000)
        return target

    def stats(self) -> dict[str, int | float | str]:
        with self._lock:
            values: dict[str, int | float | str] = dict(self._stats)
        values["directory"] = str(self.root)
        values["files"] = sum(1 for _ in self.root.glob("*.gmc")) if self.root.is_dir() else 0
        return values
