"""GraphMem 5.0 contracts.

The V5 package is self-contained.  Gate A exposes
stable domain/configuration interfaces and a read-only legacy adapter without
changing the V4/V4.1 execution path.
"""

from .config import (
    CacheIdentity,
    GraphMemRuntimeConfig,
    GraphMemV5Config,
    RetrievalRuntimeConfig,
    ServingConfig,
    config_hash,
    load_config,
    load_runtime_config,
    runtime_config_hash,
)
from .domain import (
    Conversation,
    CollectionScope,
    CanonicalEntity,
    CanonicalFact,
    CanonicalValue,
    CandidateScore,
    EntityMention,
    FactMention,
    EvidenceCertificate,
    EvidenceGroup,
    EventSkeleton,
    GraphArtifactManifest,
    GraphEdge,
    GraphNode,
    NavigationResult,
    QueryBudget,
    RunManifest,
    SemanticExtractionManifest,
    RoutingCard,
    Scene,
    Session,
    StateHead,
    TemporalInterval,
    SourceTurn,
    stable_id,
)

__all__ = [
    "EvidenceGroup",
    "EvidenceCertificate",
    "CandidateScore",
    "CanonicalEntity",
    "CanonicalFact",
    "CanonicalValue",
    "CollectionScope",
    "CacheIdentity",
    "Conversation",
    "EntityMention",
    "FactMention",
    "EventSkeleton",
    "GraphArtifactManifest",
    "GraphEdge",
    "GraphMemV5Config",
    "GraphMemRuntimeConfig",
    "GraphNode",
    "NavigationResult",
    "QueryBudget",
    "RetrievalRuntimeConfig",
    "RunManifest",
    "SemanticExtractionManifest",
    "RoutingCard",
    "Scene",
    "Session",
    "SourceTurn",
    "ServingConfig",
    "StateHead",
    "TemporalInterval",
    "config_hash",
    "load_config",
    "load_runtime_config",
    "runtime_config_hash",
    "stable_id",
]
